apiVersion: v1
data:
    grafana-admin-password: ENC[AES256_GCM,data:PqUQ1kCn8Vg1fPOs+WpN+4wnfTNYdxRRfgFjYID+wKuYLG461kGOKzooPBU=,iv:Y5qmdg43UxNB1o7L0ukLvqdkm3kWRNnTKnWMVelMAOU=,tag:FagnMTp3aYehc1LWh0iiXA==,type:str]
kind: Secret
metadata:
    name: grafana-admin-pwd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsTUZsVlhvZnBvOHpLc1Fq
            Mk0yMUN6YUI3aWxBMHJsNWw2K2lHY0p2a3hJClU4Yzh2eFVVRFZxcU1nbFFlb3Zl
            RmlkT1JNUW5IYWlwQWYyZWJ1Ny9UcnMKLS0tIEhjQ1NEOTc0WW9YQStscEgrNlh6
            UWwzL3NqVDlEb1phRllsaEZHbkduQ3MKpiQKmbvvaj34Cewqmvsx1vCdOM4eDaHb
            +xk+5e99bPQSR+l0Ll6pv2+ZmMrlyDXdPxa5hOiSkEuXOinjlC8Big==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qcwr8nuh2xvrtfsz6ljja0ffevuench8fde6kuxw06yzgtmqgypsfpw97m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-22T20:31:52Z"
    mac: ENC[AES256_GCM,data:0WBNhu2X1UHsnuxXl7jnIpY3xmkMDrMzlZ8DSu2UQEaMFS5zalXcjt8U2QUL5qd7a6isGjQkgNppak8xBOV8xbf/7gluEYw9GfO/jGMbeN//5pk9ts6WYJaQAWDEbUaPgNqNlAj+AF24HjdbOFocokkMcuPGWe+dfSm7T6pg5Hs=,iv:b6vETbPEwQYg5xBtsABhmn4LFkDa6cDbp+BLcoALe/E=,tag:9o3GQF1dNcy1wdVoYrjwxQ==,type:str]
    version: 3.13.3
