apiVersion: v1
data:
    grafana-admin-user: ENC[AES256_GCM,data:pP7K4bhtCIU=,iv:w67baZjzf4BYhHpQMCd79DTvnhP5UNH/P22TVniYcH4=,tag:TtmDXLrzipfUt6XNG313XQ==,type:str]
    grafana-admin-password: ENC[AES256_GCM,data:nQ7yfaoM5/YWCyE4D0KQ7etdwG6Vg+zWvb4bweQTguFT2QYVmJ4ZmxLLKcI=,iv:iDfPtobCNYI+PKbpJUBIok6Lql0yJUmGNaGpHL23P/E=,tag:5v8oM6mbZm/lIHucCp0rhw==,type:str]
kind: Secret
metadata:
    name: grafana-admin-pwd
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxczFYSkZ1YzJnVVdhdi9v
            bEZ4eS82bFFZbDBqYUVqM0lUUmErcmxFdWxJCkxTcEdlK3BhcklhU2ZrVUYyR1hF
            Q0MyL3V4ZkQrOW1OK0RjY0FuOWVXZ1kKLS0tIEVBc0VKN0V3Y0p0ODVDYzVJa3BH
            OXZuRjNOUm5pVCtTelFKellaQSsxNlUKyw/9ET20gIPpwdOIPDohdBcpdOs0HMJw
            su534a9USabOmz4MqbHQ2ocs7Og9Xx6sBsP8Rn6mYrNV0B00B5tGAQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qcwr8nuh2xvrtfsz6ljja0ffevuench8fde6kuxw06yzgtmqgypsfpw97m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-24T18:46:16Z"
    mac: ENC[AES256_GCM,data:r7Gz6LEdzI1XADto5AOzAC5j8XlmI5ChqAD6z+/q+e2U5u/imnp0MC0y4PXtAiWw01Ql4Y05Fp1kvOkToSDSeaNrmYNFQ9m4J4GJj//PfXnQY2PqLTUkdlMWYhfo84EB/tcdiyuCIVec8fEO2B9MLNdRAFOXVPrYRBc8Pun8EwM=,iv:sARzhQ0vEJh1hrII2q4KUsaUVgLNoxqBxGDHP9/VcJ0=,tag:ot4KMba91FefvXHwWfXAcQ==,type:str]
    version: 3.13.3
