apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:aizIuVyfy4BQwaq96ti0jq4CDmx3zZfNxOI4/fFyLYRLfx2nOjF+z8vcckzhsVoMn3fhKwUIkmZ6YsDdLRIllfR0s7r2CnIegSzW4a7XGMNfnJ1CSHxKHhUo7hbOjXu1SKUf8Lyt4hDeut5CzJIzVMUVZxttajynjpaaOI1uYyvjlDuq0nF69aUbOskBYPTJqAXK9U7dcARthPLldVOUL+7E5nTIsHYcYbEukmrFkBfwWrb9URGn2XlwMaV4f3PVGiYDMFOTKqfS0C+Z0G5YZPcoOsH6TJVEsRYreZCOm239fBA5IW9qWXQhpsY=,iv:QGDoBXyDgzvsBLTq1tDG1teVIDbDFKysuxPjvyrgeSk=,tag:EVRiiLQN2LosyNN7MlBJqA==,type:str]
kind: Secret
metadata:
    name: tunnel-credentials
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZHdvMHY5emcwVU83YlB6
            VTJHTFF0ZHJidjl2MXVGQUJGNTZtWVBkTXhnClhZVjd4d2RETFFiK05OMW53RnJK
            bDExQS93cUQzZjRhZW5FNG9yZFo3Tm8KLS0tIFd3dDE4WWNEQzlGOFk2bFBQUTJi
            MmQ0TG1SYlhSZkVwdHYxdlhZZ1pmREEKG8/7kV+ljVYfIKm6qMbNP0TT4s/RHa+X
            HO8Zrqc0wSTyUEYiLoDlGTqd/pOJvLCLQe/bs2YVsvmFj2W/REAMtA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qcwr8nuh2xvrtfsz6ljja0ffevuench8fde6kuxw06yzgtmqgypsfpw97m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T16:28:33Z"
    mac: ENC[AES256_GCM,data:gVIEcBq7me20H63xoRP1Z6Cpa2/5V6Yi1i47uct2sSKtZARc6XYvA6cCjD+atOr1q1EmN9+or6UigP52J2k/0tmcqjCQTu4jD+w+UlSdfl3/8k4tTWq7tUsuW6bsNSBA2KgxUquWV6Gs8wpFrLWJ5wQdSnw+o8bufzI1oTwQCFQ=,iv:AUfe6v8IoCd9rTTiztQJe8VQPqtkos+djHMO6IpSGPw=,tag:s0uWhp8Caa3BTTIEITx6ng==,type:str]
    version: 3.13.3
