apiVersion: v1
data:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:lCN9MN4wSmI=,iv:NoJ8VBZFZPHx7HmwRhFkQI3bB1nmr+fhDi2TQ8LMG7Q=,tag:eVy+M5S4EjNsYDi2yEP4ZQ==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:3+xtxMLX57gpUjPDaivT4fbRYNp+QLOWUbUHIEkhU9CevXTDrio0mlfwN42RmmzOWzQKS8/PDGk=,iv:IvIWfxZvtDNT+E1IKiS2EFdL7A+b0VmOFGabxhUgtGs=,tag:Xsxm0+fLjBliBYNo3x/W9g==,type:str]
kind: Secret
metadata:
  name: linkding-container-env
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoWkovSzZHaHFnblhDYlp6
        UHZvMFNtNFhFR2QzWTMvS3I2cnRhWXQ0MEVNCnpZMDE2QmJML2cyQWZrTVJ0SThH
        TS9HcEhjamx1WWRMcmtOcTVPWFpVU3cKLS0tIC81ME5tb210Q1dkL0d2c2JJR2F3
        RkF0QW9GU0xEaDZIeGpPVTRGakh5ZDQK2zr4Ez2V0+e9Y95GQVjU0Ef1LKwC/fkN
        +1xUJAOGVCRnjHzOt4FNyYUx9HtJModBxjUYhlCssWhqhQiHzdGjkA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcwr8nuh2xvrtfsz6ljja0ffevuench8fde6kuxw06yzgtmqgypsfpw97m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T16:54:35Z"
  mac: ENC[AES256_GCM,data:R/EIrTWKdDq4aZd27HXIXcvsGBjqZHFuvXepKrKachUowJ4nnYolIUAj+k7J4NxBClzTevjEsRjrdrh2QPaI47e36z/EDHZU2ckXW5vbjp1XVWmdGJDcB+0jZdCTdoT9YKkKbXsXM30OAf+jthmoDRm1Ql38JrFHy7wa7NAS3iU=,iv:K+s+OzuWu8o8oscVnI+7MBCDGlwUu/h+MgAYMqqbzNg=,tag:NlfQHtTXh28hx5Vxxr2dTA==,type:str]
  version: 3.13.3
