apiVersion: v1
data:
  LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Rvthz0NmP1s=,iv:t/zXJ25YNvWpMGXlXZmSPfiw1ixbroDGt1H27Qod5I8=,tag:TYgvUbZCH50haSh1YZl6oA==,type:str]
  LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:473NY+AsJtgI48ZQHrZMJrWZbt3Td8BtVRXBS8PHK4ejFSoY85L4Mg==,iv:7pqG/0gzOvEkjljxHTJYytZkGXO8b2dIDCEvFZbMlwY=,tag:6teArpVaKTRI0RqAC8U+tA==,type:str]
kind: Secret
metadata:
  name: linkding-container-env
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVRCsraGIrMzl3RnlScWJK
        WE5xcndJMG9MdzFyUGx1OXdRaWZ6L3RCL1NJClQ1TG9tVzhHckNtK0RqT0FVakhn
        MlNxQnlmajFBQ21aeDVxM1FHY2t1WUEKLS0tIGJJTCt3MVlBeWlra1gzS0ZhOGM3
        alp3b0pyby9CYm1nL3oxSTVQK0s0bjgK5lM+FlzAByoRWkRrImGVMadPbYdmDHad
        kAKBwGm7Ae/6my0IXVe0qG3bU+2s5oIgApDDWCyR/9km3T1SXOaS1Q==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qcwr8nuh2xvrtfsz6ljja0ffevuench8fde6kuxw06yzgtmqgypsfpw97m
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-19T17:35:19Z"
  mac: ENC[AES256_GCM,data:dL7g+6ErDmhx2mJU5fXme33bTu5bD6EbzdR860IaLAHOPuW24nNiridsEUFDgZNdRJVAnUuKjtGU88M7ItHWKxke2ZexGCzO/EY5SFJPRK6/7N/0Zx+4m/zvp5+qQ1sEMSbJm93KXnfwsdSKPvVtivqGuok61Qbbzrr48Xaf6mk=,iv:Es672HVjnmZpB8zPaab7CU2a4j8ir84V9mn3Yr+RRh4=,tag:f/0ezaEpguEVTCs8E57Jng==,type:str]
  version: 3.13.3
