apiVersion: v1
data:
    password: ENC[AES256_GCM,data:D01Q5siqIME=,iv:NcaykwQ49BOlDXe2C6FEamrb1LODHRwU7gLV16Z2308=,tag:R59bP/5f5uTPgYmnuxXbxA==,type:str]
    user: ENC[AES256_GCM,data:GMI5ZgHSegk=,iv:tsIohQVxdFdHigmCn8zdMeKO3Qzq1PvcEMMPBsfcSMU=,tag:QZXixdCBp7J08esjPLsOMg==,type:str]
kind: Secret
metadata:
    name: test-secret
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3Z29RTzAxeG9zTmR5M1Bt
            UnVTZ0ZjWFlWcEl3SFJOeEx2RElnNUtOOGdNCmlQUFV5blVHQlY4WkNybkkxa3B6
            MTM4MW9XWU1qUEYxQVRkcUZVQnNPUk0KLS0tIFQ2YjlKenUwc1pqd1dtcUg3RG1E
            TjE1dWo5b0NaRUxqNXAwclRHejJMY2sKpa7WuvPwyxHSI5G4p2WSawE7OmlN7yzT
            cOSZFmL4uuRffK96SDI61cXXQLiLiGqf8pSQjPEovvLZThIk2G5vEw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1qcwr8nuh2xvrtfsz6ljja0ffevuench8fde6kuxw06yzgtmqgypsfpw97m
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-09-19T16:07:08Z"
    mac: ENC[AES256_GCM,data:jEr0CX77igYFvDcSU6mcm5SQAzh6deQbNfoBb7I44jAXf319Azu+QWZPZ9DtorqUPdWHk51YIdU3qHlyvYRTUJbrl7jZlTsZOei16bebBCGonBH2VkS2tWBmi+l+lOqNp+NSYfaHSoSJe9gRHLqfG9gq4ZbHBKfqbCBvHI6Hyx8=,iv:RZbXRczIZSV/YG0w4dqIntBwTGoFrOX/cTq9WElINW4=,tag:tgzvdJP3rB6s8tOmgWvWNg==,type:str]
    version: 3.13.3
